# This is a basic workflow to help you get started with Actions

name: action to run  and test the main.py script

# Controls when the action will run. 
on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install bs4 selenium etc
        run: |
              python -V
              pip install requests
              pip3 install BeautifulSoup4
              pip3 install bs4
              pip3 install  selenium
              

            
      - name: run the main.py 
        run: |
              python ./main.py 
              date
